workflows:
  android-build:
    name: Android Build
    max_build_duration: 60
    scripts:
      - name: Navigate to project root
        script: cd .
      - name: Install dependencies
        script: ./gradlew dependencies
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - build/outputs/**/*.apk
